from enum import Enum, unique

@unique
class Biome(Enum):
	UNKNOWN = 0
	## TERRESTRIAL BIOMES
	WETLAND = 1
	JUNGLE = 2
	SEASONAL_FOREST = 3
	NEEDLELEAF_FOREST = 4
	GRASSLAND = 5
	DESERT_SHRUBLAND = 6
	## AQUATIC BIOMES
	FRESHWATER = 7
	SEA_FOREST = 8
	TROPICAL_REEF = 9
	ROCKY_SHALLOWS = 10
	DEEP_OCEAN = 11
	## MICROBIOTIC AND ABIOTIC BIOMES
	BARREN = 16
	SAND_SEA = 17
	ICE_SHEET = 18
	BOILING_SEA = 19
	## ASTRONOMICAL BIOMES
	MOONSCAPE = 24
	MAGMA_SEA = 25
	CRYOGEN_SEA = 26
	GAS_GIANT = 27
	STAR = 28
	NEUTRON_STAR = 29
	EVENT_HORIZON = 30
	## ARTIFICIAL BIOMES
	FARMLAND = 32
	URBAN = 33
	## SCIFI/FANTASY BIOMES
	RUINS = 34
	BIOLUMINESCENT = 40
	EVIL_INFECTED = 41
	MAGIC_GARDEN = 42
	ELEMENTAL_CHAOS = 43
	OOZE = 44
